Repository w3c/spec-generator, pull requests merged in 2018-05, with the labels that each got.

#87 ci(travis): use vars directly from Travis
  .travis.yml
Labels: bug, testing

#89 encode authorization
  test/test.js
Labels: bug, enhancement, testing

#80 Add a simple test suite (and fix a couple other things)
  .travis.yml
  README.md
  package.json
  server.js
  test/mocha.opts
  test/test.js
Labels: bug, enhancement, testing

#96 fix(package): update respec to version 20.11.2
  package.json
Labels: greenkeeper

#97 fix(package): update request to version 2.87.0
  package.json
Labels: greenkeeper
