Repository w3c/spec-generator, pull requests merged in 2018-04, with the labels that each got.

#76 fix(package): update request to version 2.85.0
  package.json
Labels: greenkeeper

#77 ci(travis): check deployed ReSpec is ok
  .travis.yml
Labels: enhancement

#78 fix(package): update respec to version 20.7.2
  package.json
Labels: greenkeeper

#82 ci(travis): authorize github requests
  .travis.yml
  package.json
Labels: enhancement, testing
